add_test([=[MacAddressTest.ParseValid]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MacAddressTest.ParseValid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MacAddressTest.ParseValid]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MacAddressTest.ParseInvalid]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MacAddressTest.ParseInvalid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MacAddressTest.ParseInvalid]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MacAddressTest.Properties]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MacAddressTest.Properties]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MacAddressTest.Properties]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Crc32Test.IsoHdlcVectors]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=Crc32Test.IsoHdlcVectors]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Crc32Test.IsoHdlcVectors]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Crc32Test.JokerPacketId]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=Crc32Test.JokerPacketId]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Crc32Test.JokerPacketId]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockAdapterTest.InitializeAndGetMac]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MockAdapterTest.InitializeAndGetMac]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockAdapterTest.InitializeAndGetMac]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockAdapterTest.TransmitUnicastWhenNotRunning]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MockAdapterTest.TransmitUnicastWhenNotRunning]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockAdapterTest.TransmitUnicastWhenNotRunning]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockAdapterTest.TransmitUnicastWhenRunning]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MockAdapterTest.TransmitUnicastWhenRunning]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockAdapterTest.TransmitUnicastWhenRunning]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockAdapterTest.TransmitBroadcast]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MockAdapterTest.TransmitBroadcast]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockAdapterTest.TransmitBroadcast]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockAdapterTest.ReceiveCallback]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=MockAdapterTest.ReceiveCallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockAdapterTest.ReceiveCallback]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HeaderTest.SerializeDeserialize]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=HeaderTest.SerializeDeserialize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HeaderTest.SerializeDeserialize]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HeaderTest.DeserializeMalformed]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=HeaderTest.DeserializeMalformed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HeaderTest.DeserializeMalformed]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HeaderTest.DeserializeInvalidType]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=HeaderTest.DeserializeInvalidType]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HeaderTest.DeserializeInvalidType]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HeaderTest.ValidateHeader]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=HeaderTest.ValidateHeader]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HeaderTest.ValidateHeader]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DedupCacheTest.BasicInsertAndContains]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=DedupCacheTest.BasicInsertAndContains]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DedupCacheTest.BasicInsertAndContains]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DedupCacheTest.EvictsOldestWhenAtCapacity]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=DedupCacheTest.EvictsOldestWhenAtCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DedupCacheTest.EvictsOldestWhenAtCapacity]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DedupCacheTest.InsertMovesToMostRecentlyUsed]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=DedupCacheTest.InsertMovesToMostRecentlyUsed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DedupCacheTest.InsertMovesToMostRecentlyUsed]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DedupCacheTest.EvictsExpired]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=DedupCacheTest.EvictsExpired]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DedupCacheTest.EvictsExpired]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[RoutingTest.CalculateTq]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=RoutingTest.CalculateTq]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[RoutingTest.CalculateTq]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NeighborTest.UpdateAndLookup]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=NeighborTest.UpdateAndLookup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NeighborTest.UpdateAndLookup]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NeighborTest.ExpireStale]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=NeighborTest.ExpireStale]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NeighborTest.ExpireStale]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NeighborTest.AllFresh]=]  /mnt/c/Projects/Joker_protocol/build_linux/joker_tests [==[--gtest_filter=NeighborTest.AllFresh]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NeighborTest.AllFresh]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/Projects/Joker_protocol/build_linux SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  joker_tests_TESTS MacAddressTest.ParseValid MacAddressTest.ParseInvalid MacAddressTest.Properties Crc32Test.IsoHdlcVectors Crc32Test.JokerPacketId MockAdapterTest.InitializeAndGetMac MockAdapterTest.TransmitUnicastWhenNotRunning MockAdapterTest.TransmitUnicastWhenRunning MockAdapterTest.TransmitBroadcast MockAdapterTest.ReceiveCallback HeaderTest.SerializeDeserialize HeaderTest.DeserializeMalformed HeaderTest.DeserializeInvalidType HeaderTest.ValidateHeader DedupCacheTest.BasicInsertAndContains DedupCacheTest.EvictsOldestWhenAtCapacity DedupCacheTest.InsertMovesToMostRecentlyUsed DedupCacheTest.EvictsExpired RoutingTest.CalculateTq NeighborTest.UpdateAndLookup NeighborTest.ExpireStale NeighborTest.AllFresh)
